/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model1(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/1.gltf')

  

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[3.21, 4.98, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.05, 1.43, 1.05]}
      />
    </group>
  )
}

useGLTF.preload('/models/1.gltf')
