/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

import * as THREE from 'three'

export default function Model3(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/3.glb')

  const texture = useTexture(['/models/textures/i9c5WMkw.jpg'])

  


  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        position={[3.21, 4.98, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.05, 1.43, 1.05]}
      >
      <meshStandardMaterial attach="material" map={texture} onUpdate={(self) => (self.needsUpdate = true)} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3.glb')
